---
- name: Clone repo branch
  git:
    repo: '{{ validator_client_repo_url }}'
    version: '{{ validator_client_repo_branch }}'
    dest: '{{ validator_client_repo_path }}'
    force: true
    update: true
  become_user: '{{ validator_client_user }}'

- name: Check if node binary exists
  stat:
    path: '{{ validator_client_repo_path }}/build/nimbus_validator_client'
  register: validator_client_bin

- name: Create timer for build script
  include_role: name=systemd-timer
  vars:
    systemd_timer_name: '{{ validator_client_build_service_name }}'
    systemd_timer_user: '{{ validator_client_user }}'
    systemd_timer_group: '{{ validator_client_group }}'
    systemd_timer_description: 'Build {{ validator_client_service_name }}'
    systemd_timer_start_on_creation: '{{ not validator_client_bin.stat.exists }}'
    systemd_timer_ionice_class: 'idle'
    systemd_timer_consul_warning: true
    systemd_timer_enabled: '{{ validator_client_build_timer_enabled }}'
    systemd_timer_frequency: '{{ validator_client_build_frequency }}'
    systemd_timer_timeout_sec: '{{ validator_client_build_timer_timeout }}'
    systemd_timer_work_dir: '{{ validator_client_service_path }}'
    systemd_timer_script_path: '{{ validator_client_service_path }}/build.sh'
