---
- name: Check if systemd timer definition is present
  stat:
    path: '/etc/systemd/system/build-{{ validator_client_service_name}}.timer'
  register: systemd_service_build_timer

- name: Stop and disable the service
  systemd_service:
    name: 'build-{{ validator_client_service_name }}.timer'
    state: 'stopped'
    enabled: false
  when: systemd_service_build_timer.stat.exists

# Allow to run the validator client if the binary is build from source
- name: Create a symlink with the build binary
  file:
    src: '{{ validator_client_repo_path }}/build/nimbus_validator_client'
    dest: '{{ validator_client_bin_path }}/nimbus_validator_client'
    state: link
  when: validator_client_update_build
  ignore_errors: yes

- name: Remove build service, timer and consul definition
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/etc/systemd/system/build-{{ validator_client_service_name }}.service'
    - '/etc/systemd/system/build-{{ validator_client_service_name }}.timer'
    - '/etc/consul/service_build_validator_client_{{ validator_client_network }}_{{ validator_client_repo_branch }}_timer.json'

- name: Reload Consul service
  systemd:
    name: consul.service
    state: reloaded
