---
- name: 'Create Consul service definition'
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ validator_client_consul_service_file_name }}'
    consul_services:
      - id:   '{{ validator_client_service_name }}'
        name: '{{ validator_client_consul_service_name }}'
        port: '{{ validator_client_keymanager_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        tags: ['{{ env }}.{{ stage }}', 'nimbus', 'validator']
        checks:
          - id:   '{{ validator_client_service_name }}-health'
            type: 'http'
            http: 'http://localhost:{{ validator_client_keymanager_port }}/eth/v1/node/version'

      - id:   '{{ validator_client_service_name }}-metrics'
        name: '{{ validator_client_consul_metrics_service_name }}'
        port: '{{ validator_client_metrics_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        tags: ['{{ env }}.{{ stage }}', 'nimbus', 'validator', 'metrics']
        meta:
          container: '{{ validator_client_service_name }}'
        checks:
          - id:   '{{ validator_client_service_name }}-metrics-health'
            type: 'http'
            http: 'http://localhost:{{ validator_client_metrics_port }}/health'
