---
- include_tasks: checks.yml
- include_tasks: install.yml
- include_tasks: user.yml
- include_tasks: config.yml
- include_tasks: update.yml
# Temporary task, remove when service to build BN has been renamed in all fleet
- include_tasks: clean-build-service.yml
- include_tasks: service.yml
- import_tasks: validators.yml
  when: validator_client_dist_validators_enabled
- include_tasks: consul.yml
