---
- include_tasks: install.yml
- include_tasks: user.yml
- include_tasks: config.yml
- include_tasks: build.yml
- include_tasks: service.yml
- import_tasks: validators.yml
  when: validator_client_dist_validators_enabled
- include_tasks: consul.yml
