---
- name: Symlink service logs folder
  file:
    src: '/var/log/service/{{ validator_client_service_name }}'
    dest: '{{ validator_client_logs_link }}'
    state: 'link'
    force: true

- name: Create systemd Unit file
  template:
    src: 'validator-client.service.j2'
    dest: '/etc/systemd/system/{{ validator_client_service_name }}.service'
    mode: 0644
  register: validator_client_service_definition

- name: Reload and restart the service
  systemd:
    name: '{{ validator_client_service_name }}.service'
    enabled: true
    daemon_reload: true
    state: |-
      {{ validator_client_service_definition.changed
       | ternary("restarted", "started") }}
