---
- name: Create user for beacon node builds
  user:
    name: '{{ validator_client_user }}'
    group: '{{ validator_client_group }}'
    shell: '/bin/bash'

- name: Set disable rebase as merge strategy
  git_config:
    scope: 'global'
    name: 'pull.rebase'
    value: 'false'
  become_user: '{{ validator_client_user }}'

- name: Sudoers file to let non-root users start jobs
  template:
    src: 'builds_sudoers.j2'
    dest: '/etc/sudoers.d/82-{{ validator_client_service_name }}-builds'
    mode: 0440

- name: Sudoers file for login as nimbus user
  template:
    src: 'nimbus_sudoers.j2'
    dest: '/etc/sudoers.d/83-{{ validator_client_service_name }}-login'
    mode: 0440
